# Generated by Django 2.0.4 on 2018-04-16 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataMining', '0002_auto_20180416_0148'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Indicator',
        ),
    ]
