# Generated by Django 2.0.4 on 2018-05-29 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='view',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
