# Generated by Django 2.0.4 on 2018-05-29 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_page_view'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Page',
        ),
    ]
